### ISSUE TITLE
Danger Suggested Output for Changelog.md Is Not Valid

### ISSUE THREAD

**Issue by jonmchan** [ruby-grape/danger#6] opened 2016-09-09 12:58 UTC
Danger complained that I was missing a changelog and presented me the following suggestion to add:

```
* [#1486](https://github.com/ruby-grape/grape/pull/1486): implemented except in values validator - [@jonmchan](https://github.com/jonmchan).
```

I copied and pasted it verbatim and danger still complained stating that it did not follow the format of the rest of the changelog.

Apparently, the first character after the PR # was supposed to be capitalized.

This is the properly formatted changelog:

```
* [#1486](https://github.com/ruby-grape/grape/pull/1486): Implemented except in values validator - [@jonmchan](https://github.com/jonmchan).
```

It would be good if danger would suggest a properly formatted changelog addition instead of suggesting something that still breaks the danger rules.

**Comment by dblock** [comment] 2016-09-09 14:10
This was opened as https://github.com/dblock/danger-changelog/issues/10, I'll close it here since the issue is in `danger-changelog`. Please feel free to contribute :)

**Closed as completed by dblock** 2016-09-09 14:10 UTC
